const accessNotAllowed = {
	status: 400,
	error: {
		code: 'access not allowed',
		message: 'please contact the developer to create your own api key',
		contact: {
			email: 'sobhanbera258@gmail.com',
		},
	},
};

const invalidQuery = {
	status: 404,
	error: {
		code: 'invalid/query',
		message: 'fetch query is not valid please try using different query than this one.',
	},
};

const pageNotFound = {
	status: 404,
	error: {
		code: 'page not found',
		message: 'this page is invalid and contains no data for you',
	},
};

const mainResponse = {
	status: 200,
	message: {
		song_query:
			'https://socbyte-backend.herokuapp.com/msc/?query={your_song_query}&key={API_KEY}',
		video_query:
			'https://socbyte-backend.herokuapp.com/video/?query={your_video_query}&key={API_KEY}',
		playlist_query:
			'https://socbyte-backend.herokuapp.com/plt/?query={your_playlist_query}&key={API_KEY}',
		search_query:
			'https://socbyte-backend.herokuapp.com/searchq/?query={incomplete_search_query}&key={API_KEY}',
	},
	info: 'api key should be generated by developer -> @sobhanbera',
};

module.exports = {
	errorData: {
		invalidQuery,
		accessNotAllowed,
		pageNotFound,
	},
	reponseData: {
		mainResponse,
	},
};
